WITH DISTINCT_PRODUCTS AS (
SELECT
DISTINCT PRODUCT_ID
FROM PURCHASE
)
SELECT
	CATEGORY,
	ROUND(AVG(PRICE-DISCOUNT)) AS AVG_PRICE
FROM
	PRODUCTS
INNER JOIN DISTINCT_PRODUCTS
ON DISTINCT_PRODUCTS.PRODUCT_ID = PRODUCTS.ID
GROUP BY CATEGORY 
